### ISSUE TITLE
ChangeOwnerAddress get error

### ISSUE THREAD

**Issue by 0127abcd** [Zondax/ledger-filecoin#76] opened 2021-07-21 07:30 UTC
it return error when i try to sign a message of changeOwnerAddress with ledger(nano s),  error:Unexpected data type

**Comment by youdou24** [comment] 2021-07-23 10:43
i have the same problem

**Comment by deanls1** [comment] 2021-07-23 10:49
same problem

**Comment by houweifeng** [comment] 2021-08-09 08:02
WithdrawBalance has the same problem。

**Comment by rllola** [comment] 2021-08-11 10:44
I would need to know what desktop wallet did you use that produce this error ?

My first thought is that this wallet send the wrong data to the ledger or in an invalid format. If you all use the same one it would help me confirm this and maybe help them fix it.

**Comment by 0127abcd** [comment] 2021-08-12 03:05
> I would need to know what wallet did you use that produce this error ?
> 
> My first thought is that this wallet send the wrong data to the ledger or in an invalid format. If you all use the same one it would help me confirm this and maybe help them fix it.

I used nanos to be owner of filecoin,  and i try to sign a message of changeOwnerAddress method, then it return me "Unexpected data type"，params of message was a string of CBOR minerId

**Comment by rllola** [comment] 2021-08-12 11:06
> I used nanos to be owner of filecoin, and i try to sign a message of changeOwnerAddress method, then it return me "Unexpected data type"，params of message was a string of CBOR addressId.

I need to know what do you use your nano s with. On your computer what software is used to talk to the ledger device ? Do you use Lotus with ledger ?

Also have you activated the advance mode on your filecoin app ?

I am looking into it. I haven't managed to reproduce it tho. The message info is helpful.

**Comment by rllola** [comment] 2021-08-12 17:14
@0127abcd 
I noticed that you are using a BLS address (start with `f3`). It required to produce a BLS signature (see https://spec.filecoin.io/algorithms/crypto/signatures/#section-algorithms.crypto.signatures.bls-signatures). Unfortunately it is not yet possible to do it on a ledger device. It will be in a few months after a firmware update.

It does not seems to be the source of this particular issue tho.

**Comment by 0127abcd** [comment] 2021-08-13 03:41
> Also have you activated the advance mode on your filecoin app ?
I activated the expert mode. I used Lotus with ledger.


> @0127abcd
> I noticed that you are using a BLS address (start with `f3`). It required to produce a BLS signature (see https://spec.filecoin.io/algorithms/crypto/signatures/#section-algorithms.crypto.signatures.bls-signatures). Unfortunately it is not yet possible to do it on a ledger device. It will be in a few months after a firmware update.
> 
> It does not seems to be the source of this particular issue tho.

I'm sorry to use the wrong information and bring you misunderstanding , that message was copied from a website, i didn't use bls address, but  secp256k1 address generated by the ledger device.

**Comment by rllola** [comment] 2021-08-13 18:52
Got it @0127abcd. No problem.

Well method 23 is definitely not implemented in ledger. The error message is wrong tho. It should be `Data is invalid : Unexpected method`.

I am not sure we can implement it. Lotus should restrict the ledger commands to the one that have been implemented.

**Comment by rllola** [comment] 2021-08-18 10:39
All methods are in fact implemented and ledger should be able to parse them (I was looking at an old version my mistake).

I haven't been able to reproduce the issue and I have added a test in zemu that test exactly it. It is passing so without more info on it I can't do much more.

**Closed** 2021-08-19 15:17 UTC
Labels: NeedsInfo, P0-Critical
