### ISSUE TITLE
Some user cannot sign FIl+ datacap Approvals

### ISSUE THREAD

**Issue by fabriziogianni7** [Zondax/ledger-filecoin#111] opened 2022-06-08 13:21 UTC
## Description
reference to this [slack message ](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1654674085582399 
)

trying to understand why some addresses cannot sign the approval message for Fil+ datacap.
I got the error Data is invalid: unexpected method
that’s the object:
```
{
From: f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi, 
GasFeeCap: 0, 
GasLimit: 0, 
GasPremium: 0, 
Method: 3, 
Nonce: 24, 
Params: ggJYIIR0sI2+0lBBYhgWLCsS32kkFZG1ziEo8bcU8x+oSwX3, 
To: f01403225, 
Value: 0
}
```
it fails only for some notaries, for others is working fine.
Looking to [this repo]( https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/methods.go#L45) ---> the Approve method is 3, as in the object.

## Additional context
To grant datacap in Fil+ program, we create a msig containing all the notaries (approvers)
this msig has a certain amount of datacap notaries can grant to clients
to grant datacap, notaries of the same msig need to propose and approve a transaction, so, 2 signatures are needed.
to propose and approve transactions we use this methods [(2 and 3)](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/methods.go#L45)
you can see [here](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/368#issuecomment-1146867430) for example a github issue where a notary proposed a datacap allocation transaction
after this, another notary with the address f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa tried to sign with no luck.
if you go to the [proposal message](https://filfox.info/en/message/bafy2bzacedqi45ugbqdjmlri5ygn4tyr5ybi5jstwfnm6r5g7b4tu3squ744k) and check the [“To’” address](https://filfox.info/en/address/f01858390) you’ll see that  f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa is included in the multisig.
to send the transaction, we map the multisig methods this way:
 ```
 3: {
      name: 'approve',
      input: {
        id: 'int',
        hash: {
          type: 'hash',
          input: {
            from: 'address',
            to: 'address',
            value: 'bigint',
            method: 'int',
            params: 'buffer',
          },
        },
      },
    },
    2: {
      name: 'propose',
      input: {
        to: 'address',
        value: 'bigint',
        method: 'int',
        params: 'buffer',
      },
    },
```
and then sign and send the transaction

we use this method of our library to approve a pending transaction --> https://github.com/keyko-io/filecoin-verifier-tools/blob/a5556414301206185c3dd13a4af34f568bd22429/api/api.js#L235
(let me know if you got access)

they can sign proposal:
[this](https://filfox.info/en/message/bafy2bzacea3knbd22u2ebarin52q6pgdb3aqggfjwbsfsu7jemgurjvs5ie34) is a proposal from f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa went correctly through
but fails to sign approvals.

looking in filfox this address was able to sign approval message like in [this case](https://filfox.info/en/message/bafy2bzaceab42z7qql3gid65pi6v4q7fmnfqqk3x3dcbrwq6ajixoialgmxbc)

:link: [zboto Link](https://app.clickup.com/t/2k56g79)

**Comment by neogeweb3** [comment] 2022-06-17 17:52
I have the exact same issue. Notary address: f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa

**Comment by fabriziogianni7** [comment] 2022-06-20 13:29
the object:
```
{
    "Version": 0,
    "To": "t01027",
    "From": "t1y6grz7kkjs5wyvg4mp5jqjl3unqt7t5ktqlrf2q",
    "Nonce": 1,
    "Value": "0",
    "GasLimit": 6481525,
    "GasFeeCap": "100706",
    "GasPremium": "99652",
    "Method": 3,
    "Params": "ggBYIGwH52jV2+1v/r+OwbwUW0Wi0CuyG3Idc5ePd1ipEiGf",
    "CID": {
        "/": "bafy2bzaced52awz5kvktv4otstdbrajyj3p7jusx23f4h3jii3x43wzxcs7cc"
    }
}
```

**Comment by neogeweb3** [comment] 2022-06-21 17:12
Object
CID: {/: 'bafy2bzaceavqhia7mo2wjcfpvzsfoifhxkzbgpwo3pwfttolozdnunl7lyq4y'}
From: "f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa"
GasFeeCap: "891501623"
GasLimit: 10155868
GasPremium: "99014"
Method: 4
Nonce: 75
Params: "glgxA7ZoDlkHE6hD16ME3JeYC8AeQ1RlUdUAMuOceTyKTfqwtTgAexl0SC/c8kUZCQ70uEcAAQAAAAAA"
To: "f06"
Value: "0"
Version: 0

**Comment by fabriziogianni7** [comment] 2022-06-30 08:47
@rllola @ftheirs hey guys do you have any update maybe? :D

**Comment by ftheirs** [comment] 2022-06-30 20:47
Hi @fabriziogianni7! Could you tell me which device are you using and also which version of the app?
I tried to reproduce this error with the latest version and I haven't received that error. Actually, the transaction was processed just fine!

**Comment by neogeweb3** [comment] 2022-07-01 23:53
Ledger nano s with filecoin v0.22.2

**Comment by ftheirs** [comment] 2022-07-03 11:52
Using 0.22.2, I was able to reproduce this issue but it's solved the 0.22.5
I see that Ledger hasn't published the last version yet. You might want to use Zondax release in the meantime. 

You might want to install it:
https://github.com/Zondax/ledger-filecoin/releases/tag/v0.22.5

Steps to install:
- Download installer_nanos.sh (or nanos_plus depending on your device)
- Give execution permission (chmod +x installer_nanos.sh)
- Install version 0.22.5 (./installer_nanos.sh load) ---> This will uninstall previous version and then install 0.22.5

Let me know if you were able to solve this, so I can close the issue 😄

**Comment by neogeweb3** [comment] 2022-07-04 01:51
I will give it a shot tomorrow, thanks in advance.

**Comment by fabriziogianni7** [comment] 2022-07-04 08:31
@ftheirs Looks working now!
I'll forward this issue comment to all the notaries using fil+. let's see if it works also for them finger crossed! 
thank you so much

**Comment by neogeweb3** [comment] 2022-07-04 19:55
It works for me too! Thanks for the help, folks! @ftheirs @fabriziogianni7

**Closed** 2022-07-04 19:59 UTC
Labels: P1-High
